spring:
  application:
    name: payment-service
  profiles:
    active: local
    include:
      - redis
      - toss
      - eureka
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
logback:
  log-path: ./logs


