spring:
  application:
    name: payment-service
  profiles:
    group:
      "local": "local, toss, default-datasource, default-db-management, default-redis, openfeign, actuator"
      "docker": "docker, toss, default-datasource, default-db-management, default-redis, openfeign, actuator"
      "prod": "prod, toss, prod-datasource, prod-db-management, prod-cache-redis, openfeign, actuator"
    active: ${PROFILE_ACTIVE:local}

#  config:
#    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}