spring:
  spring:
    datasource:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
    jpa:
      hibernate:
        ddl-auto: create-drop


service:
  member:
    base_url: localhost:8081
  product:
    base_url: localhost:8082
  order:
    base_url: localhost:8083
  payment:
    base_url: localhost:8084
  ai:
    base-url: localhost:8085